### ISSUE TITLE
Availability of code

### ISSUE THREAD

**Issue by ra-MANUJ-an** [ChnQ/TracingLLM#1]
Hello, may I inquire when the code for the paper will be made available?

**Comment by ChnQ** [comment]
> Hello, may I inquire when the code for the paper will be made available?

We apologize for the delayed response and thank you for your interest in our work! We are currently organizing the code and will do our best to make it publicly available within this month!

**Comment by ra-MANUJ-an** [comment]
@ChnQ Hi, will you be releasing the code?

**Comment by ChnQ** [comment]
Thank you for your interest in our work. The code has now been open-sourced. Thank you for your patience!
